// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: covid_data.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CovidDataClient is the client API for CovidData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CovidDataClient interface {
	GetCountriesData(ctx context.Context, in *GetCountriesDataRequest, opts ...grpc.CallOption) (*GetCountriesDataResponse, error)
	GetMostRecentDate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Date, error)
	GetAllData(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllDataResponse, error)
}

type covidDataClient struct {
	cc grpc.ClientConnInterface
}

func NewCovidDataClient(cc grpc.ClientConnInterface) CovidDataClient {
	return &covidDataClient{cc}
}

func (c *covidDataClient) GetCountriesData(ctx context.Context, in *GetCountriesDataRequest, opts ...grpc.CallOption) (*GetCountriesDataResponse, error) {
	out := new(GetCountriesDataResponse)
	err := c.cc.Invoke(ctx, "/protos.CovidData/GetCountriesData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *covidDataClient) GetMostRecentDate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Date, error) {
	out := new(Date)
	err := c.cc.Invoke(ctx, "/protos.CovidData/GetMostRecentDate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *covidDataClient) GetAllData(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllDataResponse, error) {
	out := new(GetAllDataResponse)
	err := c.cc.Invoke(ctx, "/protos.CovidData/GetAllData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CovidDataServer is the server API for CovidData service.
// All implementations must embed UnimplementedCovidDataServer
// for forward compatibility
type CovidDataServer interface {
	GetCountriesData(context.Context, *GetCountriesDataRequest) (*GetCountriesDataResponse, error)
	GetMostRecentDate(context.Context, *Empty) (*Date, error)
	GetAllData(context.Context, *Empty) (*GetAllDataResponse, error)
	mustEmbedUnimplementedCovidDataServer()
}

// UnimplementedCovidDataServer must be embedded to have forward compatible implementations.
type UnimplementedCovidDataServer struct {
}

func (UnimplementedCovidDataServer) GetCountriesData(context.Context, *GetCountriesDataRequest) (*GetCountriesDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCountriesData not implemented")
}
func (UnimplementedCovidDataServer) GetMostRecentDate(context.Context, *Empty) (*Date, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMostRecentDate not implemented")
}
func (UnimplementedCovidDataServer) GetAllData(context.Context, *Empty) (*GetAllDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllData not implemented")
}
func (UnimplementedCovidDataServer) mustEmbedUnimplementedCovidDataServer() {}

// UnsafeCovidDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CovidDataServer will
// result in compilation errors.
type UnsafeCovidDataServer interface {
	mustEmbedUnimplementedCovidDataServer()
}

func RegisterCovidDataServer(s grpc.ServiceRegistrar, srv CovidDataServer) {
	s.RegisterService(&CovidData_ServiceDesc, srv)
}

func _CovidData_GetCountriesData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCountriesDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CovidDataServer).GetCountriesData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.CovidData/GetCountriesData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CovidDataServer).GetCountriesData(ctx, req.(*GetCountriesDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CovidData_GetMostRecentDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CovidDataServer).GetMostRecentDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.CovidData/GetMostRecentDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CovidDataServer).GetMostRecentDate(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CovidData_GetAllData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CovidDataServer).GetAllData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.CovidData/GetAllData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CovidDataServer).GetAllData(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CovidData_ServiceDesc is the grpc.ServiceDesc for CovidData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CovidData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.CovidData",
	HandlerType: (*CovidDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCountriesData",
			Handler:    _CovidData_GetCountriesData_Handler,
		},
		{
			MethodName: "GetMostRecentDate",
			Handler:    _CovidData_GetMostRecentDate_Handler,
		},
		{
			MethodName: "GetAllData",
			Handler:    _CovidData_GetAllData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "covid_data.proto",
}
